# Generated by Django 4.2.4 on 2023-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('imc', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('bajo', 'Bajo Peso'), ('normal', 'Peso Normal'), ('sobrepeso', 'Sobrepeso')], max_length=10, null=True)),
            ],
        ),
    ]
